apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: x20jdv4xn-nodejs 
  janus-idp.io/tekton: x20jdv4xn-nodejs
  backstage.io/kubernetes-id: x20jdv4xn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x20jdv4xn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml